#!/bin/bash
# version-bump.sh - Automatic semantic versioning based on commits
# Usage: ./version-bump.sh [major|minor|patch]

set -e

# Get current version from package.json
CURRENT_VERSION=$(node -p "require('./package.json').version")
echo "Current version: $CURRENT_VERSION"

# Parse version components
MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)

# Check last commit message for version bump trigger
LAST_COMMIT=$(git log -1 --pretty=%B)
COMMIT_TYPE=$(echo "$LAST_COMMIT" | grep -oE '^(feat|fix|docs|chore|refactor|breaking|major)' | head -1)

echo "Last commit: $LAST_COMMIT"
echo "Commit type: $COMMIT_TYPE"

# Determine bump type
BUMP_TYPE="${1:-auto}"

if [ "$BUMP_TYPE" = "auto" ]; then
    if echo "$LAST_COMMIT" | grep -qE "^(breaking|major|BREAKING CHANGE)"; then
        BUMP_TYPE="major"
    elif [ "$COMMIT_TYPE" = "feat" ]; then
        BUMP_TYPE="minor"
    else
        BUMP_TYPE="patch"
    fi
fi

echo "Bump type: $BUMP_TYPE"

# Calculate new version
case $BUMP_TYPE in
    major)
        MAJOR=$((MAJOR + 1))
        MINOR=0
        PATCH=0
        ;;
    minor)
        MINOR=$((MINOR + 1))
        PATCH=0
        ;;
    patch)
        PATCH=$((PATCH + 1))
        ;;
    *)
        echo "Unknown bump type: $BUMP_TYPE"
        exit 1
        ;;
esac

NEW_VERSION="$MAJOR.$MINOR.$PATCH"
echo "New version: $NEW_VERSION"

# Update package.json
node -e "
const fs = require('fs');
const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
pkg.version = '$NEW_VERSION';
fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\\n');
console.log('Updated package.json to $NEW_VERSION');
"

# Update VERSION file
echo "$NEW_VERSION" > VERSION
echo "Updated VERSION file"

# Get current git info
CURRENT_COMMIT=$(git rev-parse --short HEAD)
CURRENT_BRANCH=$(git branch --show-current)
BUILD_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Regenerate version.ts with CURRENT commit
cat > app/version.ts << EOF
// Auto-generated version file
// Regenerated by version-bump.sh on $BUILD_TIMESTAMP
// DO NOT EDIT MANUALLY

export const VERSION = "$NEW_VERSION";
export const VERSION_MAJOR = $MAJOR;
export const VERSION_MINOR = $MINOR;
export const VERSION_PATCH = $PATCH;
export const BUILD_DATE = "$BUILD_TIMESTAMP";
export const GIT_COMMIT = "$CURRENT_COMMIT";
export const GIT_BRANCH = "$CURRENT_BRANCH";
EOF

echo "Regenerated app/version.ts with commit: $CURRENT_COMMIT"

# Stage changes
git add package.json VERSION app/version.ts

# Amend commit to include version bump
git commit --amend --no-edit

echo "Version bumped to $NEW_VERSION (commit: $CURRENT_COMMIT)"
