// Auto-generated version file
// Regenerated by version-bump.sh on 2026-02-19T12:12:21Z
// DO NOT EDIT MANUALLY

export const VERSION = "2.17.5";
export const VERSION_MAJOR = 2;
export const VERSION_MINOR = 17;
export const VERSION_PATCH = 5;
export const BUILD_DATE = "2026-02-21T22:50:28.169Z";
export const GIT_COMMIT = "4998b04";
export const GIT_BRANCH = "main";
