// Auto-generated version file
// Regenerated by version-bump.sh on 2026-02-19T12:12:21Z
// DO NOT EDIT MANUALLY

export const VERSION = "2.17.12";
export const VERSION_MAJOR = 2;
export const VERSION_MINOR = 17;
export const VERSION_PATCH = 12;
export const BUILD_DATE = "2026-02-22T11:22:40.387Z";
export const GIT_COMMIT = "4998b04";
export const GIT_BRANCH = "main";
